import { z } from 'zod';

/**
 * A feed-item key is generated by the frontend from data it already received
 * (e.g. "ann-<announcementId>"). It is only ever stored against the
 * authenticated user's own id, so it needs no ownership semantics — just a
 * length/charset bound so an arbitrarily large or exotic string can't be
 * persisted.
 */
export const notificationKeyParamsSchema = z.object({
  notificationKey: z
    .string()
    .min(1)
    .max(200)
    .regex(/^[A-Za-z0-9_:.-]+$/, 'notificationKey may only contain letters, numbers, and _ : . -'),
});

export type NotificationKeyParams = z.infer<typeof notificationKeyParamsSchema>;
